[toc]

# Numpy tile

In [1]:
import numpy as np

a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [2]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [3]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

# References
[numpy.tile — NumPy v1.19 Manual](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)