[toc]

# Numpy transpose

transpose 函数的效果很简单，但是含义并不太好理解。

## [batch_size, seq_len, embedding_size]

In [28]:
import numpy as np

x = np.arange(12).reshape(2,2,3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


## [seq_len, batch_size, embedding_size]

In [24]:
ret1 = x.transpose(1, 0, 2)
print(ret1)
print(ret1.shape)

[[[ 0  1  2]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 9 10 11]]]
(2, 2, 3)


为了容易理解，我们给每个轴赋予含义。假设我们的三维坐标分别表示 [batchs_size, seq_len, embedding_size]

那么 x 可以如此拆分。

第0个batch 是

```
[[ 0  1  2]
  [ 6  7  8]]
```

第1个batch是

```
[[ 6  7  8]
  [ 9 10 11]]
```

而 ret1 的维度是 [seq_len, batch_size, embedding_size]

相当于将所有 batch 的 embedding 都提取出来，作为第一个元素，所有的 batch 的第二个 embedding 都提取出来，作为第二个元素。


### [embedding_size, batch_size, seq_len]

In [25]:
ret2 = x.transpose(2, 0, 1)
print(ret2)
print(ret2.shape)

[[[ 0  3]
  [ 6  9]]

 [[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]]
(3, 2, 2)


ret2 的维度是 `[embedding_size, batch_size, seq_len]`，可以看作将所有的 embedding 的第一个维度提取出来，分batch 来放置。

第 0 个embedding 的维度上，第 0 个batch 的值为 `[0, 3]`，第 1 个 batch 的值为 `[6,9]`，因此得到了 ret2 的 embedding_size 维度的第 0 个元素（这个元素是一个 2 x 2 的矩阵）

```
[0, 3]
[6, 9]
```

第 1 个 embedding 的维度上，第 0 个 batch 的值为 `[1, 4]`，第 1 个 batch 的值为 `[7, 10]`，因此得到了 ret2 的 embedding_size 维度的第 1 个元素

```
[1, 4]
[7, 10]
```