# Numpy 数组索引与切片

In [3]:
import numpy as np

## 一维数组的索引与切片


 一维数组的索引与切片和 list 相似

In [4]:
a = np.arange(1,20,2) # 不包含最后一个元素

In [8]:
a[3] # 7
a[1:4] # array([3, 5, 7])
a[:2] # array([1, 3])
a[::-1] # array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

7

array([3, 5, 7])

array([1, 3])

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

## 多维数组的索引与切片

In [10]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
b[1,1,2]     # 第2层第2行第3列
b[0, 2, :]   # 第1层第3行的所有数据
b[0]         # 第1层数据
b[0, ...]    # 第1层数据
b[:, 1]      # 第2行数据
b[:,:,1]     # 第2列数据
b[..., 1]    # 第2列数据
b[0, ::2, -2]  # 第0层中每隔1行选取该行倒数第2个数

18

array([ 8,  9, 10, 11])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

array([[ 1,  5,  9],
       [13, 17, 21]])

array([[ 1,  5,  9],
       [13, 17, 21]])

array([ 2, 10])

## bool 索引

In [17]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
b >= 15

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [21]:
# 注意是一个 1d array
b[b>=15] # array([15, 16, 17, 18, 19, 20, 21, 22, 23])

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [27]:
# 反选，不是 not(b>=15) 也不是 !(b>=15)
b[~(b>=15)] # array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
b[(b>=5) & (b<=15)] # 逻辑运算符and、or在布尔数组中无效

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**注意**：
数组的切片跟列表最重要的区别在于：
数组切片是原始数组的视图（view），它与原始数组共享同一块数据存储空间。即数据不会被复制，视图上的任何修改都会直接反映到源数组。
如果需要数组切片是一个副本而不是视图，可以用copy方法进行显式复制。

In [42]:
c = np.arange(24).reshape(2,3,4)
c_slice = c[0, 1]       # array([4, 5, 6, 7])
c_copy = c[0, 1].copy() # array([4, 5, 6, 7])

In [43]:
c_slice[1] = 666
c_slice
c

array([  4, 666,   6,   7])

array([[[  0,   1,   2,   3],
        [  4, 666,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [45]:
c_copy[1] = 999
c_copy
c

array([  4, 999,   6,   7])

array([[[  0,   1,   2,   3],
        [  4, 666,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])